Add partners component
rapidez/website pull request #18
Opened 2023-09-21 12:52 UTC by JimmyHoenderdaal

2023-09-21 14:08 UTC, Roene-JustBetter approved these changes

2023-09-22 06:05 UTC, Jade-GG requested changes

2023-09-22 06:05 UTC, Jade-GG commented on resources/views/components/package/card.blade.php
> +@props(['logo' => '', 'title' => '', 'category' => ''])
No need to give empty strings as defaults when you're checking them anyway

2023-09-22 06:05 UTC, Jade-GG commented on resources/views/components/package/group.blade.php
> +<label for="{{ $id }}" {{ $label->attributes->class('bg-gray-100 p-1 text-center max-md:flex-1 md:min-w-[200px] md:p-2') ?? '' }}>
`$label->attributes` when you have `label` as a prop?

2023-09-22 06:40 UTC, Jade-GG approved these changes

2023-09-22 07:35 UTC, Roene-JustBetter approved these changes

2023-09-22 09:35 UTC, merged